spring:
  application:
    name: Customer-Service
  main:
    web-application-type: none
  config:
    import: optional:file:./env.properties,optional:file:../env.properties
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:customer_service;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://localhost:9200}
    username: ${SPRING_ELASTICSEARCH_USERNAME:}
    password: ${SPRING_ELASTICSEARCH_PASSWORD:}
  cloud:
    consul:
      enabled: ${CONSUL_ENABLED:false}
    discovery:
      enabled: ${CONSUL_DISCOVERY_ENABLED:false}

sentry:
  dsn: ${SENTRY_DSN:}
  enabled: ${SENTRY_ENABLED:false}
